# Generated by Django 2.2.5 on 2020-05-20 03:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('plam', '0003_auto_20200516_1710'),
    ]

    operations = [
        migrations.CreateModel(
            name='Image',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('picture', models.ImageField(upload_to='images/')),
                ('title', models.CharField(max_length=200)),
            ],
        ),
    ]
